version: '3.8'  # Версия синтаксиса Docker Compose

services:  # Список сервисов (контейнеров), которые мы хотим запустить

  zookeeper:  # Kafka требует Zookeeper для управления метаданными брокеров (пока что)
    image: confluentinc/cp-zookeeper:7.5.0  # Образ Zookeeper от Confluent
    container_name: zookeeper  # Явное имя контейнера (необязательно, но удобно)
    ports:
      - "2181:2181"  # Порт, на котором работает Zookeeper (Kafka будет к нему подключаться)
    environment:  # Переменные окружения для настройки Zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181  # Основной порт для клиентов
      ZOOKEEPER_TICK_TIME: 2000  # Тайминг-сессии в миллисекундах (внутренний параметр)

  kafka:  # Основной брокер Kafka
    image: confluentinc/cp-kafka:7.5.0  # Образ Kafka от Confluent (совместим с Zookeeper выше)
    container_name: kafka  # Явное имя контейнера Kafka
    ports:
      - "9092:9092"  # Порт для подключения снаружи (localhost)
      - "29092:29092"  # Порт для подключения из других контейнеров
    environment:  # Конфигурация Kafka через переменные окружения
      KAFKA_BROKER_ID: 1  # ID брокера в кластере (если бы их было несколько)
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Адрес Zookeeper, к которому подключится Kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,CONTAINER://kafka:29092
      # Список адресов, по которым Kafka "рекламирует" себя клиентам.
      # - PLAINTEXT://localhost:9092 — для приложений, запускаемых **на хосте (вне Docker)**.
      # - CONTAINER://kafka:29092 — для **других контейнеров**, обращающихся по имени kafka внутри docker-сети.

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTAINER://0.0.0.0:29092
      # Список интерфейсов, на которых Kafka слушает входящие соединения.
      # - 0.0.0.0 означает "слушать на всех интерфейсах".
      # - Нужно явно указать оба — и для localhost, и для внутренней docker-сети.

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTAINER:PLAINTEXT
      # Протоколы безопасности для каждого listener'а.
      # - Оба используют PLAINTEXT — небезопасное соединение без TLS (достаточно для локальной разработки).

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Эта настройка определяет, сколько **копий (реплик)** Kafka будет хранить для служебного топика __consumer_offsets.
      # Этот топик используется Kafka, чтобы отслеживать, какие сообщения уже были прочитаны консьюмерами.
      #
      # Значение 1 означает:
      # - Храним только **одну копию** данных (без резервного дублирования).
      # - Это **приемлемо для локальной разработки**, где один Kafka-брокер и отказоустойчивость не критична.
      #
      # В продакшене:
      # - Обычно ставят `3` — это значит, что каждый фрагмент (partition) будет дублироваться на 3-х разных брокерах.
      # - Это защищает от потери данных, если один из брокеров выйдет из строя.
      #
      # ⚠️ Если поставить больше, чем реально поднято брокеров — Kafka не сможет создать __consumer_offsets и завалится.

    depends_on:
      - zookeeper  # Kafka должна стартовать после того, как будет готов Zookeeper

  kafka-init:  # Имя сервиса — отдельный контейнер, задачей которого является создать топики при старте
    image: confluentinc/cp-kafka:7.5.0  # Используем тот же образ Kafka, т.к. он содержит утилиты kafka-topics.sh и cub
    container_name: kafka-init  # Явное имя контейнера для удобства
    depends_on:
      - kafka  # Указываем, что этот контейнер должен стартовать только после kafka (иначе она может быть не готова)
    volumes:
      - ./create-topics.sh:/tmp/create-topics.sh  # Примонтировать локальный скрипт create-topics.sh внутрь контейнера в /tmp
      # Так контейнер "увидит" файл скрипта и сможет его выполнить
    entrypoint: ["/bin/bash", "/tmp/create-topics.sh"]  # Команда, которую контейнер выполнит при запуске
    # Это переопределение стандартной entrypoint'а образа Kafka

  kafka-ui: # 🔍 Веб-интерфейс для Kafka (https://github.com/provectus/kafka-ui)
    image: provectuslabs/kafka-ui  # 🐳 Используем готовый образ Kafka UI от Provectus
    ports:
      - "8088:8080"  # 🌐 Пробрасываем внутренний порт 8080 (UI) наружу на 8088
    environment:
      KAFKA_CLUSTERS_0_NAME: local  # 📛 Название кластера, как он будет отображаться в интерфейсе
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092  # 📡 Адрес Kafka-брокера для подключения
    depends_on:
      - kafka  # ⏳ Запускать только после запуска Kafka, иначе не сможет подключиться
