spring:
  application:
    name: async-order-system-kafka

  kafka:
    bootstrap-servers: localhost:9092  # Адрес Kafka-брокера. Если Kafka запущена через Docker, это обычно порт 9092 на localhost.

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Сериализатор ключа. Обычно ключ — это строка, например, order ID ("123").

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # Сериализатор значения. Преобразует Java-объекты (например, Order) в JSON перед отправкой в Kafka.

    consumer:
      group-id: async-order-system-consumer-<UNIQUE_NAME>
      # 🔥 Уникальный group-id для каждого сервиса!
      # Это нужно, чтобы каждый получал ВСЕ сообщения из топика, а не делил их с другими сервисами.

      auto-offset-reset: earliest
      # Если нет сохранённого offset, читать с самого начала (полезно для dev/тестирования).

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        # Разрешить десериализацию объектов из всех пакетов.
        # В проде желательно указать конкретные trusted пакеты для безопасности.

  docker:
    compose:
      lifecycle-management: start_and_stop  # Автоматически запускать/останавливать Kafka и Zookeeper через Docker Compose
      readiness:
        timeout: 15s  # Время ожидания готовности Kafka и Zookeeper

server:
  port: 8086

logging:
  level:
    root: INFO
    org.chumin.asyncordersystem: DEBUG  # Включаем детальное логирование для своего приложения
    org.apache.kafka: WARN  # Kafka логгирует только предупреждения и ошибки
