spring:
  application:
    name: async-order-system-kafka
  kafka:
    bootstrap-servers: localhost:9092  # ????? Kafka-???????. ? ????? ?????? ? ????????? ??????, ???????????? ?? Docker (??????? ???? 9092)

    producer:  # ????????? Kafka-??????????? (KafkaTemplate)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # ???????????? ????? ????????? (Kafka ??????? ???????????? ?????? ? ?????).
      # ????? ???? ? ?????? (????????, order ID "123"), ? ?? ?? ??????????? ? ????????? ????.

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # ???????????? ???????? ????????? ? ??? ?????? Order ????? ???????????? ? JSON.
      # ??? ?????? ??? ?????? ? DTO/????????, Spring ??? ??????????? ? ?????? JSON.
    consumer:
      auto-offset-reset: earliest  # ????? ?????????? ?????? ? ?????? ??????, ???? ??? ???????????? offset
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  # ????????? ??????????????? ??? ?????? (?????? ??? dev, ?? ?????????? ? ?????)

  docker:
    compose:
      lifecycle-management: start_and_stop  # ????????? ? ????? docker-compose ?????? ? ???????????
      readiness:
        timeout: 15s  # ????? ???????? ?????????? ???????? (Kafka, Zookeeper ? ?.?.)

server:
  port: 8086

logging:
  level:
    root: INFO
    org.chumin.asyncordersystem: DEBUG  # ???????? ???? ??????? ????????
    org.apache.kafka: WARN  # Kafka-????????? ???? ? ??????????



